### PR TITLE
Changed  '-' to '.-' in barcode function to prevent number-matrix sub…

### PR DESCRIPTION
**Pull request by lachrimae**
…traction type error.

This bugfix was suggested by [Philip Egger](https://github.com/pegger0709) [here.](https://github.com/Eetion/Eirene.jl/issues/5)

### CODE REVIEW

**Comment by lachrimae** [comment]
Found another such error that was blocking plotting the betti curves.

**Comment by lachrimae** [comment]
Commit 5bbb2db will now produce Betti curve plots.

**Comment by henselman-petrusek** [comment]
Many thanks!

**Comment by lachrimae** [comment]
No worries!

**Pull request merged**
